<a href="https://colab.research.google.com/github/Aparna-Sakshi/DLFA/blob/main/18MA20007_DLFA_Assignment0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment-0 : Building a neural network
### Name: Aparna Sakshi
### Roll No.:18MA20007

## Feed Forward Neural Network

In [ ]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
from matplotlib import pyplot as plt
from torchvision import transforms, datasets

In [ ]:
class FFNN(nn.Module):
  def __init__(self):
    super(FFNN,self).__init__()
    self.fc1 = nn.Linear(784,100)
    self.sigmoid=nn.Sigmoid()
    self.fc2 = nn.Linear(100, 10)
    
  def forward(self, x):
    x=self.fc1(x)
    x=self.sigmoid(x)
    x=self.fc2(x)
    x=F.softmax(x,dim=1)
    #print(x.size())
    return x

In [ ]:
net = FFNN()
print(net)


FFNN(
  (fc1): Linear(in_features=784, out_features=100, bias=True)
  (sigmoid): Sigmoid()
  (fc2): Linear(in_features=100, out_features=10, bias=True)
)


In [ ]:
params = list(net.parameters())
print("No. of parameters: ", len(params))
print("Dimensions of first layer weights: ", params[0].size())#weights of fc1
print("Dimensions of first layer bias: ", params[1].size())#biases of fc1
print("Dimensions of second layer weights", params[2].size())#weights of fc2
print("Dimensions of second layer bias: ", params[3].size())#biases of fc2

totalParams = 0
for param in params:
  #print(param.size())
  totalParams += np.sum(np.prod(param.size()))
print("Total number of parameters: ", totalParams)


No. of parameters:  4
Dimensions of first layer weights:  torch.Size([100, 784])
Dimensions of first layer bias:  torch.Size([100])
Dimensions of second layer weights torch.Size([10, 100])
Dimensions of second layer bias:  torch.Size([10])
Total number of parameters:  79510


In [ ]:
apply_transform = transforms.Compose([transforms.ToTensor()])
Batchsize = 256
trainset = datasets.MNIST(root = './data', train=True, download=True, transform=apply_transform)
trainLoader = torch.utils.data.DataLoader(trainset, batch_size=Batchsize, shuffle=True, num_workers=4) #Creating dataLoader

In [ ]:
for i,data in enumerate(trainLoader):
  inputs, labels = data 
  outputs=[]  
  for ip in inputs:
    op = net.forward(inputs.view(-1,28*28))
    outputs.append(np.argmax(op.detach().numpy()))
  #print(outputs)
  

In [ ]:
inputs.view(-1, inputs.shape[0]).shape

torch.Size([784, 96])

In [ ]:
data1=next(iter(trainLoader))

In [ ]:
input1, label=data1

In [ ]:
input1.shape

torch.Size([256, 1, 28, 28])

In [ ]:
label

tensor([2, 6, 6, 5, 4, 8, 4, 2, 3, 4, 2, 5, 2, 2, 6, 1, 1, 2, 4, 2, 5, 3, 1, 0,
        6, 8, 3, 7, 0, 1, 3, 5, 1, 3, 3, 6, 8, 6, 2, 8, 8, 0, 4, 9, 6, 2, 1, 2,
        9, 5, 9, 9, 9, 2, 9, 6, 0, 9, 5, 9, 2, 0, 2, 3, 7, 7, 5, 7, 2, 6, 3, 7,
        0, 8, 6, 7, 2, 4, 2, 4, 8, 6, 7, 7, 3, 6, 6, 8, 8, 5, 5, 7, 7, 2, 6, 5,
        9, 5, 6, 4, 3, 8, 2, 2, 4, 2, 5, 1, 6, 3, 9, 2, 3, 7, 2, 7, 2, 7, 8, 5,
        1, 9, 6, 9, 4, 2, 0, 6, 0, 1, 7, 7, 6, 9, 8, 2, 7, 6, 3, 0, 5, 7, 7, 2,
        9, 7, 6, 6, 0, 4, 8, 4, 7, 6, 0, 0, 9, 7, 5, 4, 6, 5, 7, 3, 2, 1, 3, 9,
        7, 9, 7, 2, 2, 9, 8, 7, 7, 2, 8, 1, 6, 7, 9, 7, 4, 6, 1, 5, 4, 1, 2, 9,
        0, 3, 7, 9, 3, 7, 0, 8, 1, 9, 0, 9, 6, 5, 7, 7, 3, 4, 6, 9, 1, 4, 2, 5,
        5, 8, 8, 6, 1, 0, 7, 0, 6, 8, 5, 3, 2, 6, 3, 3, 1, 7, 1, 2, 6, 2, 9, 0,
        4, 6, 1, 1, 0, 1, 9, 0, 4, 5, 9, 6, 2, 7, 6, 9])

In [ ]:
net(input1.view(input1.shape[0],-1))

torch.Size([256, 10])


tensor([[0.1510, 0.0668, 0.0644,  ..., 0.0860, 0.0964, 0.1539],
        [0.1520, 0.0654, 0.0649,  ..., 0.0848, 0.0984, 0.1563],
        [0.1575, 0.0660, 0.0650,  ..., 0.0856, 0.0955, 0.1521],
        ...,
        [0.1560, 0.0661, 0.0643,  ..., 0.0836, 0.0940, 0.1560],
        [0.1588, 0.0642, 0.0647,  ..., 0.0858, 0.0958, 0.1522],
        [0.1573, 0.0666, 0.0671,  ..., 0.0844, 0.0960, 0.1495]],
       grad_fn=<SoftmaxBackward>)

## Convolutional neural network

In [ ]:
class LeNet(nn.Module):
  def __init__(self):
    super(LeNet, self).__init__()
    self.conv1 = nn.Conv2d(1,6,5) #1 input image channel, 6 output channels, 5X5 square convolution kernel
    self.pool1 = nn.MaxPool2d(2,stride=2)
    self.conv2 = nn.Conv2d(6,16,5)
    self.pool2 = nn.MaxPool2d(2,stride=2)
    self.linear1 = nn.Linear(16*4*4,120) #28-5+1=24, #24/2=12, #12-5+1=8, #8/2=4
    self.linear2 = nn.Linear(120,84)
    self.linear3 = nn.Linear(84,10)
    
  def forward(self, x):
    x=F.relu(self.conv1(x))
    x=self.pool1(x)
    x=F.relu(self.conv2(x))
    x=self.pool2(x)
    x=F.relu(self.linear1(x))
    x=F.relu(self.linear2(x))
    x=F.relu(self.linear3(x))
    x=F.softmax(x,dim=1)
    #print(x.size())
    return x


In [ ]:
conv_net = LeNet()
print(conv_net)


LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (linear1): Linear(in_features=256, out_features=120, bias=True)
  (linear2): Linear(in_features=120, out_features=84, bias=True)
  (linear3): Linear(in_features=84, out_features=10, bias=True)
)


In [ ]:
params = list(conv_net.named_parameters())
print('No. of parameters: ', len(params))

totalParams = 0
for name,param in params:
  print(name, "-->", param.shape)
  totalParams += np.sum(np.prod(param.size()))
print("Total number of parameters: ", totalParams)


No. of parameters:  10
conv1.weight --> torch.Size([6, 1, 5, 5])
conv1.bias --> torch.Size([6])
conv2.weight --> torch.Size([16, 6, 5, 5])
conv2.bias --> torch.Size([16])
linear1.weight --> torch.Size([120, 256])
linear1.bias --> torch.Size([120])
linear2.weight --> torch.Size([84, 120])
linear2.bias --> torch.Size([84])
linear3.weight --> torch.Size([10, 84])
linear3.bias --> torch.Size([10])
Total number of parameters:  44426


In [ ]:
apply_transform = transforms.Compose([transforms.Resize(32), transforms.ToTensor()])
Batchsize = 256
trainset = datasets.MNIST(root='./data', train = True, download=False, transform=apply_transform)
trainLoader = torch.utils.data.DataLoader(trainset, batch_size=Batchsize, shuffle=True)#creating dataloader

In [ ]:
for i,data in enumerate(trainLoader):
  inputs,labels = data
  print(inputs.shape)
  #outputs = net(inputs)



torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([256, 1, 32, 32])
torch.Size([25

In [ ]:
data1 = next(iter(trainLoader))

In [ ]:
input1,label=data1

In [ ]:
label

tensor([1, 5, 1, 9, 4, 4, 4, 4, 1, 4, 1, 1, 3, 0, 0, 2, 9, 2, 8, 4, 6, 3, 3, 1,
        9, 7, 7, 4, 1, 1, 5, 0, 4, 0, 5, 7, 4, 5, 0, 1, 2, 5, 4, 7, 2, 7, 4, 0,
        1, 1, 9, 9, 2, 7, 1, 1, 2, 5, 5, 7, 9, 8, 3, 6, 8, 6, 2, 0, 2, 0, 4, 3,
        0, 9, 5, 2, 0, 6, 8, 7, 0, 1, 1, 6, 7, 4, 1, 9, 9, 4, 7, 6, 8, 2, 7, 3,
        5, 6, 8, 5, 9, 0, 7, 6, 1, 2, 8, 7, 0, 4, 6, 1, 2, 5, 7, 4, 5, 9, 5, 6,
        4, 7, 2, 3, 2, 5, 8, 7, 6, 6, 3, 2, 6, 0, 4, 8, 9, 1, 2, 6, 5, 5, 6, 5,
        1, 4, 9, 9, 4, 6, 8, 5, 0, 8, 7, 8, 2, 0, 4, 0, 1, 7, 1, 2, 6, 3, 5, 2,
        7, 2, 2, 9, 2, 6, 6, 5, 7, 8, 2, 6, 1, 6, 9, 8, 8, 4, 0, 0, 2, 4, 6, 3,
        4, 4, 0, 1, 2, 4, 6, 3, 9, 7, 4, 2, 6, 7, 0, 4, 9, 6, 4, 9, 8, 0, 6, 9,
        9, 3, 9, 4, 5, 9, 4, 5, 5, 9, 8, 5, 6, 3, 4, 1, 5, 4, 1, 2, 5, 8, 1, 1,
        7, 8, 1, 2, 8, 6, 9, 2, 7, 4, 0, 7, 0, 7, 5, 7])